### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by keidyalmonte** [keidyalmonte/Plant-Hub#3]
The To-Do List encaptures the stub functions needed for each part. This would allow me to properly prepare my code for prototyping.

**Parts Included:**

1. _Humidity Sensor (DHT11)_ - returns two values
- [x] def setup()
- [x] def read_humidity() 
- [x] def read_temp() 

2. _Photosensor (DV-P8103)_
- [x] def setup()
- [x] def read_light_level()
- [x] def output()

3. _STEMMA Soil Sensor_
- [x] def setup()
- [x] def soil_moisture()
- [x] def soil_temp()

4. _LCD Display_
- [x] def setup()
- [x] def turn_on()
- [x] def turn_off()
- [x] def write_text()

5. _Potentiometer_
- [x] def setup()
- [x] def set_resistance()

6. _Buttons_
- [x] def setup()
- [x] def detect_push()
- [x] def detect_interrupt()

**Comment by keidyalmonte** [comment]
The basic stub functions were added, along with the demo to test the functions. A few changes were made to the names, to clearly specify which function worked for what part. Below are the new names.

**Humidity Sensor**
- def setup_humidity()
- def read_humidity()
- def read_temp()

**Photosensor**
- def setup_photosensor()
- def read_light_level()
- def output_photosensor()

**STEMMA Soil Sensor**
- def setup_soil()
- def soil_moisture()
- def soil_temp()

**LCD Display**
- def setup_display()
- def turn_on_display()
- def turn_off_display()
- def write_text()

**Potentiometer**
- def setup_potentiometer()
- def set_resistance_p()

**Buttons**
- def setup_buttons()
- def detect_push()
- def detect_interrupt()
